#!/bin/bash

# Ejemplos de uso del sistema de logs centralizados
# Este archivo contiene comandos comunes para copiar y pegar

echo "════════════════════════════════════════════════════════════════"
echo "  📋 EJEMPLOS DE USO - LOGS CENTRALIZADOS"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "🔹 COMANDOS BÁSICOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ver ayuda completa"
echo "./view-logs.sh help"
echo ""
echo "# Ver todos los logs"
echo "./view-logs.sh all"
echo ""
echo "# Ver logs solo de microservicios"
echo "./view-logs.sh services"
echo ""

echo "🔹 LOGS POR SERVICIO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Tournaments Service"
echo "./view-logs.sh tournaments"
echo ""
echo "# Matches Service"
echo "./view-logs.sh matches"
echo ""
echo "# Auth Service"
echo "./view-logs.sh auth"
echo ""
echo "# Teams Service"
echo "./view-logs.sh teams"
echo ""
echo "# Notifications Service"
echo "./view-logs.sh notifications"
echo ""

echo "🔹 LOGS DE INFRAESTRUCTURA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# PostgreSQL"
echo "./view-logs.sh postgres"
echo ""
echo "# MongoDB"
echo "./view-logs.sh mongodb"
echo ""
echo "# Redis"
echo "./view-logs.sh redis"
echo ""
echo "# RabbitMQ"
echo "./view-logs.sh rabbitmq"
echo ""

echo "🔹 MONITOREO EN TIEMPO REAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Seguir logs del servicio de torneos"
echo "./view-logs.sh follow tournaments"
echo ""
echo "# Seguir logs del servicio de partidos"
echo "./view-logs.sh follow matches"
echo ""
echo "# Seguir logs de RabbitMQ"
echo "./view-logs.sh follow rabbitmq"
echo ""

echo "🔹 ANÁLISIS Y DEBUGGING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ver solo errores de todos los servicios"
echo "./view-logs.sh errors"
echo ""
echo "# Ver estadísticas de logs"
echo "./view-logs.sh stats"
echo ""
echo "# Buscar por texto específico"
echo "docker-compose logs | grep 'tournament_id'"
echo ""
echo "# Buscar errores en un servicio específico"
echo "docker-compose logs tournaments-service | grep -i error"
echo ""

echo "🔹 EXPORTACIÓN DE LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Exportar todos los logs a archivos"
echo "./export-logs.sh"
echo ""
echo "# Exportar logs de un servicio específico"
echo "./export-logs.sh tournaments-service"
echo ""
echo "# Exportar a un directorio personalizado"
echo "./export-logs.sh all ./my-logs"
echo ""

echo "🔹 COMANDOS DOCKER COMPOSE DIRECTOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ver últimas 50 líneas de un servicio"
echo "docker-compose logs --tail=50 tournaments-service"
echo ""
echo "# Ver logs con timestamps"
echo "docker-compose logs -t tournaments-service"
echo ""
echo "# Ver logs desde hace 1 hora"
echo "docker-compose logs --since=1h"
echo ""
echo "# Ver logs de múltiples servicios"
echo "docker-compose logs tournaments-service matches-service"
echo ""
echo "# Seguir logs de todos los servicios"
echo "docker-compose logs -f"
echo ""

echo "🔹 FILTRADO AVANZADO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Buscar errores y excepciones"
echo "docker-compose logs | grep -iE 'error|exception|failed|fatal'"
echo ""
echo "# Contar número de errores"
echo "docker-compose logs | grep -ic error"
echo ""
echo "# Ver solo logs de nivel ERROR"
echo "docker-compose logs | grep 'ERROR'"
echo ""
echo "# Buscar por ID de torneo"
echo "docker-compose logs | grep 'tournament_id: 123'"
echo ""
echo "# Ver logs con contexto (3 líneas antes y después)"
echo "docker-compose logs | grep -A 3 -B 3 'error'"
echo ""

echo "🔹 MANTENIMIENTO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Limpiar logs antiguos (requiere confirmación)"
echo "./view-logs.sh clean"
echo ""
echo "# Ver tamaño de logs"
echo "docker ps -q | xargs docker inspect --format='{{.Name}} {{.LogPath}}' | while read name path; do [ -f \"\$path\" ] && echo \"\$name: \$(du -h \"\$path\" | cut -f1)\"; done"
echo ""
echo "# Reiniciar servicios (rota logs)"
echo "docker-compose restart"
echo ""

echo "🔹 CASOS DE USO COMUNES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# 1. Debugging durante desarrollo"
echo "./view-logs.sh follow tournaments"
echo ""
echo "# 2. Investigar un error reportado"
echo "./view-logs.sh tournaments | grep 'error'"
echo ""
echo "# 3. Monitoreo general del sistema"
echo "./view-logs.sh stats"
echo "./view-logs.sh errors"
echo ""
echo "# 4. Análisis post-incidente"
echo "./export-logs.sh"
echo "docker-compose logs --since='2024-01-19T10:00:00' --until='2024-01-19T11:00:00'"
echo ""
echo "# 5. Verificar comunicación entre servicios"
echo "docker-compose logs tournaments-service matches-service | grep -i 'rabbitmq\\|event'"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "💡 TIP: Para copiar un comando, simplemente selecciónalo y copia"
echo "════════════════════════════════════════════════════════════════"
